databases:
  - name: ThriftMVP Production DB
    databaseName: thrift
    user: thrift

services:
  - type: web
    name: ThriftMVP Production
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn thriftshop.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ThriftMVP Production DB
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 1
