# Generated by Django 3.2.12 on 2022-05-05 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_alter_membershipplan_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='credit_currency',
        ),
    ]
