# Generated by Django 3.2.12 on 2022-04-22 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0003_cloudtype_hosting_industry_platform_service_techstack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudtype',
            name='mvp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_types', to='mvp.mvp'),
        ),
        migrations.AlterField(
            model_name='hosting',
            name='mvp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosting', to='mvp.mvp'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='mvp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industries', to='mvp.mvp'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='mvp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='mvp.mvp'),
        ),
        migrations.AlterField(
            model_name='service',
            name='mvp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='mvp.mvp'),
        ),
        migrations.AlterField(
            model_name='techstack',
            name='mvp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_stack', to='mvp.mvp'),
        ),
    ]
