# Generated by Django 3.2.12 on 2022-04-22 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mvp', '0004_auto_20220422_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='mvp',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mvps', to=settings.AUTH_USER_MODEL),
        ),
    ]
