# Generated by Django 3.2.12 on 2022-04-23 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0005_mvp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mvp',
            name='code_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mvp',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='preview_images'),
        ),
        migrations.CreateModel(
            name='MvpImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='mvp_images')),
                ('mvp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mvp.mvp')),
            ],
        ),
    ]
