# Generated by Django 3.2.12 on 2022-05-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0009_alter_failurereason_mvps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudtype',
            name='mvps',
            field=models.ManyToManyField(blank=True, null=True, related_name='cloud_types', to='mvp.Mvp'),
        ),
        migrations.AlterField(
            model_name='failurereason',
            name='mvps',
            field=models.ManyToManyField(blank=True, null=True, related_name='failure_reasons', to='mvp.Mvp'),
        ),
        migrations.AlterField(
            model_name='hosting',
            name='mvps',
            field=models.ManyToManyField(blank=True, null=True, related_name='hosting', to='mvp.Mvp'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='mvps',
            field=models.ManyToManyField(blank=True, null=True, related_name='industries', to='mvp.Mvp'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='mvps',
            field=models.ManyToManyField(blank=True, null=True, related_name='platforms', to='mvp.Mvp'),
        ),
        migrations.AlterField(
            model_name='service',
            name='mvps',
            field=models.ManyToManyField(blank=True, null=True, related_name='services', to='mvp.Mvp'),
        ),
        migrations.AlterField(
            model_name='techstack',
            name='mvps',
            field=models.ManyToManyField(blank=True, null=True, related_name='tech_stack', to='mvp.Mvp'),
        ),
    ]
