# Generated by Django 3.2.12 on 2022-05-03 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0010_auto_20220501_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='mvp',
            name='status',
            field=models.CharField(choices=[('review', 'In Review'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='review', max_length=20),
        ),
    ]
