# Generated by Django 3.2.12 on 2022-05-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_stripe_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='users/avatars/spaceguy.webp', upload_to='users/avatars'),
        ),
    ]
